configfile: "config.yaml"


include: "rules/common.smk"
include: "rules/adapter.smk"
include: "rules/demux.smk"
include: "rules/trim.smk"
include: "rules/stats.smk"


rule all:
    input:
        expand("reads/final/{library}.fastq", library=get_library_ids()),
        "reads/seqkit_stats.tsv",
