configfile: "config.yaml"


include: "rules/common.smk"
include: "rules/adapter.smk"
include: "rules/demux.smk"
include: "rules/trim.smk"


rule all:
    input:
        expand("reads/linker_trimmed/{sublib}.fastq", sublib=sublib_ids),
