configfile: "config.yaml"


include: "rules/common.smk"
include: "rules/adapter.smk"
include: "rules/demux.smk"


rule all:
    input:
        expand(
            "reads/{pool}/unknown.fastq",
            pool=get_pool(),
        ),
